service: moneyfast

image: edoardodep/moneyfast

servers:
  web:
    - 188.245.178.80

proxy:
  ssl: true
  hosts:
    - moneyfast.edodep.com

registry:
  username: edoardodep
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - OPENAI_API_KEY
    - EMAIL_PRINCIPESSA
  clear:
    SOLID_QUEUE_IN_PUMA: true

volumes:
  - "moneyfast-storage:/rails/storage"
  - "moneyfast-database:/rails/storage/*.sqlite3"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

builder:
  arch: arm64

ssh:
  user: root

deploy:
  migrate: true